petbccufscar/beecrowd

Iniciante/1080/1080.c, Iniciante/1080/README.md, Iniciante/1094/1094.c, Iniciante/1094/README.md, Iniciante/1095/1095.c, Iniciante/1095/README.md
=> Adicionando exercícios 1080, 1094 e 1095

Iniciante/1145/1145.c, Iniciante/1145/README.md, Iniciante/1146/1146.c, Iniciante/1146/README.md, Iniciante/1149/1149.c, Iniciante/1149/README.md
O 1149 foi um desafio de esfinge pra entender, mas deu tudo certo.
=> Adicionando 1145, 1146 e 1149

Iniciante/1187/1187.c, Iniciante/1187/README.md, Iniciante/1188/1188.c, Iniciante/1188/README.md, Iniciante/1189/1189.c, Iniciante/1189/README.md
Na moral, mexer com matriz não é coisa do bem não
=> Adicionando 1187, 1188 e 1189

Iniciante/2166/README.md, Iniciante/2551/2551.c, Iniciante/2551/README.md, Iniciante/2552/2552.c, Iniciante/2552/README.md
Esqueci de adicionar o link do problema completo no 2166, já foi corrigido.
=> Adicionando 2551 2552 e alterando 2166

Iniciante/2630/2630.c, Iniciante/2630/README.md
=> Adicionando 2630

Iniciante/3040/3040.c, Iniciante/3040/README.md
Visto que o URI estava off quando foi feito o exercicio, favor verificar se está correto.
=> Adicionando 3040

Iniciante/3037/3037.c, Iniciante/3037/README.md
Não consegui testar, pois o URI estava em manutenção
=> Adicionando 3037

Strings/1367/README.md, Strings/2484/2484.c, Strings/2484/README.md
Fiz uma correção no link do 1367, só pra entrar no padrão mesmo
=> Adicionado 2484

Python/Iniciante/2750.py, Python/Iniciante/3047.py, Python/Iniciante/3055.py, Python/Iniciante/3091.py
Adicionado os exercícios da semana passada
Editando um exercício antigo, graças a correção do @matheusvictorello  :D
=> Adicionando 3047, 3055, 3091

Python/Iniciante/1156.py, Python/Iniciante/1176.py, Python/Iniciante/1178.py, Python/Iniciante/1182.py
=> Adicionando exercício 1178

Python/Strings/2692.py
[2692](https://www.beecrowd.com.br/judge/pt/problems/view/2692)
=> Adicionando 2692

Python/Iniciante/2140.py
[2140](https://www.beecrowd.com.br/judge/pt/problems/view/2140)
=> Adicionando 2140

Python/Iniciante/2162.py
[2162](https://www.beecrowd.com.br/judge/pt/problems/view/2162)
=> Adicionando 2162

Python/Iniciante/2164.py
[2164](https://www.beecrowd.com.br/judge/pt/problems/view/2164)
=> Adicionando 2164

Python/Strings/2292.py
[2292](https://www.beecrowd.com.br/judge/pt/problems/view/2292)
Maldito timeout do beecrowd
=> Adicionando 2292

Python/Strings/2049.py
[2049](https://www.beecrowd.com.br/judge/pt/problems/view/2049)
=> Adicionando 2049

Python/Strings/2954.py
[2954 - O Jogo](https://www.beecrowd.com.br/judge/pt/problems/view/2954)
=> Adicionando 2954

Python/Strings/3141.py
[3141 - Dúvida Etária](https://www.beecrowd.com.br/judge/pt/problems/view/3141)
=> Adicionando 3141

Python/Strings/2697.py
[2697 - Sequencia Completa de Naebbirac](https://www.beecrowd.com.br/judge/pt/problems/view/2697)
=> Adicionando 2697

Python/Strings/2588.py
[2588](https://www.beecrowd.com.br/judge/pt/problems/view/2588)
=> Adicionando 2588

Python/Iniciante/1145.py, Python/Iniciante/1146.py, Python/Iniciante/2310.py
Eu fiz o negócio errado então **esse pull também tem os commits de #269**, favor revisar ele primeiro...
[2310](https://www.beecrowd.com.br/judge/pt/problems/view/2310)
=> Adicionando 2310

Python/Iniciante/1145.py, Python/Iniciante/1146.py
Primeiro pull request de verdade...
Vejam se exagerei nos comentários
[1146](https://www.beecrowd.com.br/judge/pt/problems/view/1146), [1145](https://www.beecrowd.com.br/judge/pt/problems/view/1145)
=> Adicionando 1146, 1145

Python/Iniciante/2031.py
[2031](https://www.beecrowd.com.br/judge/pt/problems/view/2031)
O beecrowd não tem python 3.10... tive que fazer com if/else ;-;
=> Adicionando 2031

Python/Iniciante/2313.py
[2313](https://www.beecrowd.com.br/judge/pt/problems/view/2313)
=> Adicionando 2313

Python/Strings/1664.py
[1664 - Bullshit Bingo](https://www.beecrowd.com.br/judge/pt/problems/view/1664)
Quem criou esse foi o demônio
=> Adicionando 1664

Python/Strings/2025.py
[2025](https://www.beecrowd.com.br/judge/pt/problems/view/2025)
=> Adicionando 2025

Python/Strings/2690.py
[2690](https://www.beecrowd.com.br/judge/pt/problems/view/2690)
Tinha esquecido do print de debugging 🤦
=> Adicionando 2690

Python/Strings/2691.py
[2691](https://www.beecrowd.com.br/judge/pt/problems/view/2691)
=> Adicionando 2691
